name: X

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Playlist
        env:
          u: ${{ secrets.s }}
          f: ${{ secrets.f }}
        run: |
          curl -sSL "$u" -o "$f"

      - name: Commit Changes
        env:
          f: ${{ secrets.f }}
          gu: ${{ secrets.gu }}
          ge: ${{ secrets.ge }}
        run: |
          import datetime, os
          timestamp = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
          msg = f"Last Update Time: {timestamp}"
          os.system(f'git config --global user.name "{os.environ["gu"]}"')
          os.system(f'git config --global user.email "{os.environ["ge"]}"')
          os.system(f'git add {os.environ["f"]}')
          os.system(f'git commit -m "{msg}" || echo "No changes to commit"')
          os.system('git push')
          print(f"Commit message used: {msg}")
        shell: python
